### ISSUE TITLE
The number of memos is always loading

### ISSUE THREAD

**Issue by yihanglee-cn** [lincolnthalles/memospot#49]
### Describe the bug

- System: Windows 11 x64
- Memospot version: 0.1.3

### Steps to reproduce

1. Copy data from Docker server (0.18.2) to Memospot default data folder
2. Open Memospot, Memos, pictures are normal, but the number of memos is always loading
![PixPin_2024-02-27_10-07-32](https://github.com/lincolnthalles/memospot/assets/31716253/76408d3e-fd47-454f-8373-2257aeb7f29a)

**Comment by yihanglee-cn** [comment]
@lincolnthalles Sorry to bother you, but the problem still exists. The memos version is 0.20.1, memospot version is 0.1.4.
![image](https://github.com/lincolnthalles/memospot/assets/31716253/d35fc9bb-9da9-43bb-b602-c3ca7838001e)

**Comment by lincolnthalles** [comment]
> @lincolnthalles Sorry to bother you, but the problem still exists. The memos version is 0.20.1, memospot version is 0.1.4. 

It turns out the last fix was incomplete. It worked on my machine because I have Go installed and Memos was using the timezone data from there. (Go uses [fallbacks](https://pkg.go.dev/time#LoadLocation) for this.)

I changed the builds to always include timezone data, so it will prevent this from happening on any system.
https://github.com/lincolnthalles/memos-builds/commit/1432e3d2710dd801a63f372d87f9ad4fe725c5dd

You can run the server updater script again and it should get you a working build.
https://github.com/lincolnthalles/memospot?tab=readme-ov-file#windows-updater-script

This is from a clean Windows 11 install, after installing 0.1.3/0.1.4 and updating the server.
![image](https://github.com/lincolnthalles/memospot/assets/7476810/25331495-9013-4f1e-aa8b-89271833b22a)

**Comment by yihanglee-cn** [comment]
> > @lincolnthalles Sorry to bother you, but the problem still exists. The memos version is 0.20.1, memospot version is 0.1.4.很抱歉打扰您，但问题仍然存在。memos 版本为 0.20.1，memospot 版本为 0.1.4。
> 
> It turns out the last fix was incomplete. It worked on my machine because I have Go installed and Memos was using the timezone data from there. (Go uses [fallbacks](https://pkg.go.dev/time#LoadLocation) for this.)事实证明，最后一个修复程序不完整。它在我的机器上工作，因为我安装了 Go，而 Memos 正在使用那里的时区数据。（Go 为此使用回退。
> 
> I changed the builds to always include timezone data, so it will prevent this from happening on any system.我将构建更改为始终包含时区数据，因此它可以防止这种情况在任何系统上发生。 [lincolnthalles/memos-builds@1432e3dLincolnthalles/备忘录-builds@ 1432e3d ](https://github.com/lincolnthalles/memos-builds/commit/1432e3d2710dd801a63f372d87f9ad4fe725c5dd)
> 
> You can run the server updater script again and it should get you a working build.您可以再次运行服务器更新程序脚本，它应该会为您提供一个有效的版本。 https://github.com/lincolnthalles/memospot?tab=readme-ov-file#windows-updater-script
> 
> This is from a clean Windows 11 install, after installing 0.1.3/0.1.4 and updating the server.这是在安装 11/0.1.3 并更新服务器后进行的干净的 Windows 0.1.4 安装。 ![image](https://private-user-images.githubusercontent.com/7476810/312850835-25331495-9013-4f1e-aa8b-89271833b22a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjI5OTAsIm5iZiI6MTcxMDQyMjY5MCwicGF0aCI6Ii83NDc2ODEwLzMxMjg1MDgzNS0yNTMzMTQ5NS05MDEzLTRmMWUtYWE4Yi04OTI3MTgzM2IyMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTMyNDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM4NzVlOWZjNGEzMDExYTE3NzRjNTNjYWJmYzdiYTBjNGUxNWMwZDlhOGM0ZGY2NzdjN2Q3NGUwOWI2OGM2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e-rbOIf05aaigSNdFzy5G1FNhhHdk806r2PDDss3bv8)

Thanks for your hard work✌️
