### ISSUE TITLE
Language reset back to English when restart client

### ISSUE THREAD

**Issue by yihanglee-cn** [lincolnthalles/memospot#9]
### Describe the bug

Language reset back to English when restart client

### Steps to reproduce

1. Open Settings-->Preferences-->Language, Choose Chinese, Language switch successful
2. Restart client
3. Language reset back to English

**Comment by lincolnthalles** [comment]
I believe you upgraded to v0.18.0 or v0.18.1, right?

I'm able to reproduce the issue with those server versions, but not with the bundled v0.17.1.

Memos had lots of API changes recently and also on the browser storage.

This happens due to Memospot using a dynamic port on each server restart and Memos not properly recovering the user settings from the database on a new session.

I will address this on a future release by saving the first free port found to a config file and only changing that if this port ever becomes in use. This should make this issue very rare even if Memos upstream doesn't get a correction that fits Memospot, with the plus of minimizing the WebView storage usage, as sessions will be frequently reused.

I already created a bug report on upstream https://github.com/usememos/memos/issues/2659

**Comment by yihanglee-cn** [comment]
Yes, I updated it to version 0.18.1. Thank you very much for your attention and wish you a happy Christmas in advance.🎄
